var c=n=>n?.nodeType===Node.ELEMENT_NODE;import{actions as d,store as m,intercept as f}from"@neptune";import{ReactiveRoot as Q}from"@neptune/components";import{$ as A,html as _,useMemo as b,useCleanup as k}from"@neptune/voby";var u=new Map,I=()=>[f(["playQueue/ADD_LAST","playQueue/ADD_NEXT"],([{mediaItemIds:n}])=>{n.forEach(e=>{u.has(e)&&u.get(e)(!0)})}),f("playQueue/REMOVE_ELEMENT",([{uid:n}])=>{let e=m.getState().playQueue,t=e.currentIndex;for(let o=t+1;o<e.elements.length&&e.elements[o].priority==="priority_keep";o++)if(e.elements[o].uid===n){let r=e.elements[o].mediaItemId;u.has(r)&&u.get(r)(!1);return}}),f("playbackControls/MEDIA_PRODUCT_TRANSITION",([{playbackContext:n}])=>{let e=Number(n.actualProductId),t=m.getState().playQueue,o=t.currentIndex;for(let r=o+1;r<t.elements.length&&t.elements[r].priority==="priority_keep";r++){let s=t.elements[r].mediaItemId;if(s===e)return;u.has(s)&&u.get(s)(!0)}u.has(e)&&u.get(e)(!1)})],g=n=>{let e=n.attributes,t={};for(let o=0;o<e.length;o++){let r=e[o];t[r.name]=r.value}return t},N=(n,e)=>{let t=A(!1),{elements:o,currentIndex:r}=m.getState().playQueue;for(let a=r+1;a<o.length&&o[a].priority==="priority_keep";a++)o[a].mediaItemId===e&&t(!0);u.set(e,t),k(()=>u.delete(e));let s=b(()=>"#"+(t()?"detail-view__trashcan":"player__queue-add")),i=b(()=>t()?"Remove from queue":"Add to queue"),p=n.querySelector('button[data-test="add-to-playlist-button"]');if(!p)return null;let q=g(p),v=g(p.querySelector("svg"));return _`
        <button
            ...${q}
            data-test="quick-queue"
            aria-label=${i}
            title=${i}
            style="padding: 4px;"
            onClick=${async()=>{let{elements:a,currentIndex:x}=m.getState().playQueue;for(let l=x+1;l<a.length&&a[l].priority==="priority_keep";l++)if(a[l].mediaItemId===e){d.playQueue.removeAtIndex({index:l}),d.message.messageInfo({message:"Removed from play queue"}),t(!1);return}d.playQueue.addLast({mediaItemIds:[e],context:{type:"user"}}),d.message.messageInfo({message:"Added to play queue"}),t(!0)}}
        >
            <svg ...${v}>
                <use href=${s}></use>
            </svg>
        </button>
    `},S=(n,e,t,o,r)=>{let s=n.querySelector(`button[data-test="${e}"]`);if(s!==null)return;let i=n.querySelector(t);if(i!==null&&(s=o,c(s)))return i.parentElement.insertBefore(s,r instanceof Element?r:r?n.querySelector(r):i)},h=(n,e)=>{S(n,"quick-queue",'button[data-test="add-to-playlist-button"]',Q({children:()=>N(n,Number(e))}),'button[data-test="add-to-playlist-button"]')};var E=[],y=new MutationObserver(n=>{for(let e of n)if(e.type==="childList"){for(let t of e.addedNodes)if(c(t)){let o=t.querySelectorAll('div[data-test="tracklist-row"]');o.length!==0&&T(o)}}}),T=async n=>{for(let e of n){let t=e.getAttribute("data-track-id");if(t==null)return;h(e,t)}},M=()=>{y.disconnect(),y.observe(document.body,{childList:!0,subtree:!0})};M();E.push(...I());var P=()=>{E.forEach(n=>n()),y.disconnect()};export{P as onUnload,M as updateObserver};
